config/routes.rb
Rails.application.routes.draw do
  resources :lista_racas
  #root 'welcome#index'
  root 'cachorros#index'
  get 'welcome/index'

  resources :cachorros
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cachorro.rb
class Cachorro < ApplicationRecord	
	belongs_to :lista_raca 
	def self.pesquisa(query)
		where("nome_cao like ?", "%#{query}%")
	end
	validates :castrado, presence: true
	validates :nascimento, presence: true
	validates :nome_cao, presence: true
	validates :nome_dono, presence: true
	validates :telefone, presence: true
	validates :data_ultima_vez_petshop, presence: true
	validates :lista_raca, presence: true
	validates :sexo, presence: true

end

app/models/lista_raca.rb
class ListaRaca < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cachorros_controller.rb
class CachorrosController < ApplicationController
  before_action :set_cachorro, only: [:show, :edit, :update, :destroy]
  before_action :set_lista_raca, only: [:show, :edit]

  # GET /cachorros
  # GET /cachorros.json
  def index
    if params[:pesquisar]
      @cachorros = Cachorro.pesquisa(params[:pesquisar]).paginate(:page => params[:page], :per_page => 50) 
    else
      @cachorros = Cachorro.all.paginate(:page => params[:page], :per_page => 50) 
    end   
  end

  # GET /cachorros/1
  # GET /cachorros/1.json
  def show
  end

  # GET /cachorros/new
  def new
    @cachorro = Cachorro.new    
  end

  # GET /cachorros/1/edit
  def edit
  end

  # POST /cachorros
  # POST /cachorros.json
  def create
    @cachorro = Cachorro.new(cachorro_params)

    respond_to do |format|
      if @cachorro.save
        format.html { redirect_to @cachorro, notice: 'Cachorro was successfully created.' }
        format.json { render :show, status: :created, location: @cachorro }
      else
        format.html { render :new }
        format.json { render json: @cachorro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cachorros/1
  # PATCH/PUT /cachorros/1.json
  def update
    respond_to do |format|
      if @cachorro.update(cachorro_params)
        format.html { redirect_to @cachorro, notice: 'Cachorro was successfully updated.' }
        format.json { render :show, status: :ok, location: @cachorro }
      else
        format.html { render :edit }
        format.json { render json: @cachorro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cachorros/1
  # DELETE /cachorros/1.json
  def destroy
    @cachorro.destroy
    respond_to do |format|
      format.html { redirect_to cachorros_url, notice: 'Cachorro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cachorro
      @cachorro = Cachorro.find(params[:id])
    end

    def set_lista_raca
      @lista_racas = ListaRaca.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cachorro_params
      params.require(:cachorro).permit(:lista_raca_id, :castrado, :nascimento, :nome_cao, :nome_dono, :telefone, :data_ultima_vez_petshop, :sexo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cachorros_helper.rb
module CachorrosHelper
end

app/helpers/lista_racas_helper.rb
module ListaRacasHelper
end

app/views/cachorros/_form.html.erb
<%= form_for @cachorro, :html => { :class => "form-horizontal cachorro" } do |f| %>

  <% if @cachorro.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@cachorro.errors.count, "error") %> prohibited this cachorro from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @cachorro.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  <%# raspagem de dados para retornar a raça %>
  <div class="form-group">
    <%= f.label :lista_raca_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.collection_select(:lista_raca_id, ListaRaca.all,
                  :id, :nome_raca, {:prompt => 'Selecione...'}, {class: "form-control"}) %>      
    </div>
    <%=f.error_span(:lista_raca_id) %>
  </div>
  <%# castrado %>
  <div class="form-group">
    <%= f.label 'É castrado?', :class => 'control-label col-lg-2' %>
    <div class="radio-inline">
      <p><%= f.radio_button :castrado, 'sim' %> <%= f.label 'Sim' %></p>    
      <p><%= f.radio_button :castrado, 'nao' %> <%= f.label 'Não' %></p>    
    </div>
    <%=f.error_span(:castrado) %>
  </div>
  <div class="form-group">
    <%= f.label :nascimento, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.date_field :nascimento, :class => 'form-control' %>
    </div>
    <%=f.error_span(:nascimento) %>
  </div>
  <div class="form-group">
    <%= f.label :nome_cao, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :nome_cao, :class => 'form-control' %>
    </div>
    <%=f.error_span(:nome_cao) %>
  </div>
  <div class="form-group">
    <%=f.label :sexo, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select(:sexo, 
                    options_for_select([["Macho", "M"], ["Fêmea", "F"]], @cachorro.sexo),
                    {include_blank: false}, {class: "form-control"}) %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :nome_dono, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :nome_dono, :class => 'form-control' %>
    </div>
    <%=f.error_span(:nome_dono) %>
  </div>
  <div class="form-group">
    <%= f.label :telefone, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :telefone, :class => 'form-control' %>
    </div>
    <%=f.error_span(:telefone) %>
  </div>
  <div class="form-group">
    <%= f.label :data_ultima_vez_petshop, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.date_field :data_ultima_vez_petshop, :class => 'form-control' %>
    </div>
    <%=f.error_span(:data_ultima_vez_petshop) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                cachorros_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/cachorros/edit.html.erb
<%- model_class = Cachorro -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/cachorros/index.html.erb
<%- model_class = Cachorro -%>
<div class="page-header">
  <h1>PetShop Cão Feliz</h1>
  <h3><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h3>
</div>

<%# Pesquisa o cão pelo nome do dono%>
<%= form_tag(cachorros_path, :method => :get) do %>
  <div class="form-group">   
    <div class="col-lg-10">
      <%= text_field_tag 'pesquisar', nil, placeholder: 'Digite o nome do cão...', :class => 'form-control' %>
    </div>   
    <%= submit_tag 'Pesquisar', :class => 'btn btn-primary' %>
  </div>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nome_cao) %></th>
      <th><%= model_class.human_attribute_name(:sexo) %></th>
      <th><%= model_class.human_attribute_name(:nome_dono) %></th>
      <th><%= model_class.human_attribute_name(:lista_raca_id) %></th>
      <th><%= model_class.human_attribute_name(:castrado) %></th>
      <th><%= model_class.human_attribute_name(:nascimento) %></th>      
      <th><%= model_class.human_attribute_name(:telefone) %></th>
      <th><%= model_class.human_attribute_name(:data_ultima_vez_petshop) %></th>     
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @cachorros.each do |cachorro| %>
      <tr>
        <td><%= link_to cachorro.id, cachorro_path(cachorro) %></td>
        <td><%= cachorro.nome_cao %></td>
        <td><%= cachorro.sexo %></td>
        <td><%= cachorro.nome_dono %></td>
        <td><%= cachorro.lista_raca.nome_raca %></td>
        <td><%= cachorro.castrado %></td>
        <td><%= cachorro.nascimento %></td>       
        <td><%= cachorro.telefone %></td>
        <td><%= cachorro.data_ultima_vez_petshop %></td>        
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      cachorro_path(cachorro), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_cachorro_path(cachorro), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      cachorro_path(cachorro),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_cachorro_path,
            :class => 'btn btn-primary' %>
<br />
<%= will_paginate @cachorros %>

app/views/cachorros/new.html.erb
<%- model_class = Cachorro -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/cachorros/show.html.erb
<%- model_class = Cachorro -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:lista_raca_id) %>:</strong></dt>
  <dd><%= @cachorro.lista_raca.nome_raca %></dd>
  <dt><strong><%= model_class.human_attribute_name(:castrado) %>:</strong></dt>
  <dd><%= @cachorro.castrado %></dd>
  <dt><strong><%= model_class.human_attribute_name(:nascimento) %>:</strong></dt>
  <dd><%= @cachorro.nascimento %></dd>
  <dt><strong><%= model_class.human_attribute_name(:nome_cao) %>:</strong></dt>
  <dd><%= @cachorro.nome_cao %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sexo) %>:</strong></dt>
  <dd><%= @cachorro.sexo %></dd>
  <dt><strong><%= model_class.human_attribute_name(:nome_dono) %>:</strong></dt>
  <dd><%= @cachorro.nome_dono %></dd>
  <dt><strong><%= model_class.human_attribute_name(:telefone) %>:</strong></dt>
  <dd><%= @cachorro.telefone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:data_ultima_vez_petshop) %>:</strong></dt>
  <dd><%= @cachorro.data_ultima_vez_petshop %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              cachorros_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_cachorro_path(@cachorro), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              cachorro_path(@cachorro),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Petshop</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>